### PR TITLE
Dialog Semiconductor example and library documentation

### PR DESCRIPTION
**Pull request by nbezembinder1**
See commit comments

### CODE REVIEW

**Comment by gokr** [comment]
I am wondering about the jsdoc stuff, seems there is something that caused your commit to use different filenames, like evothings-libraries_libs_evothings_easyble_easyble.js.html being renamed to easyble_easyble.js.html. No idea where the "evothings-libraries_libs_evothings_"-prefix comes from.

**Comment by nbezembinder1** [comment]
That's weird, didn't notice that before, I'll try to generate the documentation again using jsdoc

**Comment by nbezembinder1** [comment]
Hmm, seems like there is something wrong with the `jsdoc-baseline` package. Running `npm install` on a new clone returns a 404 ERROR: `jsdoc-baseline is not in the npm registry`. Could you try to generate the docs?

I'm on a Windows 7 machine by the way, running npm version 2.14.20

**Comment by gokr** [comment]
I have cherry picked https://github.com/evothings/evothings-doc/pull/108/commits/403cb2f6f17247fe982de0a1eadd7a4e08efc40d

Then I generated lib-doc myself, that should be it, right?

**Comment by nbezembinder1** [comment]
That's right, thanks!

I will look into the whole jsdoc thing to see what's the problem, not sure why I'm getting this error.

**Comment by gokr** [comment]
If you do "npm install" now I think it will work - I had to change the package.json to point elsewhere for jsdoc-baseline.

**Pull request closed without merging**
